# Generated by Django 4.0.1 on 2022-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='article name')),
                ('description', models.TextField(verbose_name='article description')),
                ('scope_of_application', models.TextField(verbose_name='scope of application')),
                ('diameter', models.IntegerField(verbose_name='diameter')),
                ('length', models.FloatField(verbose_name='length')),
                ('color', models.CharField(max_length=64, verbose_name='color')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='category name')),
                ('description', models.TextField(verbose_name='category description')),
            ],
        ),
    ]
