# Generated by Django 4.0.1 on 2022-01-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_diameter_alter_product_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='shop.subgroup'),
        ),
        migrations.AlterField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='shop.section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='shop.card'),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='shop.group'),
        ),
    ]
